services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db

  api:
    container_name: api
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
      - 6500:6500

  ui:
    container_name: ui
    depends_on:
      - api
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 5173:5173

volumes:
  mongo_volume:
